apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexora-frontend
  namespace: nexora
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - nexora.prdxso.dev
      secretName: nexora-frontend-tls
  rules:
    - host: nexora.prdxso.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexora-frontend
                port:
                  number: 80
