apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nexora-frontend-policy
  namespace: nexora
spec:
  podSelector:
    matchLabels:
      app: nexora-frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - port: 80
          protocol: TCP
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
